---
- hosts: webservers
  user: vagrant
  sudo: yes
  gather_facts: no
  roles:
    - common
    - webservers

- hosts: dbservers
  user: vagrant
  sudo: yes
  gather_facts: no
  roles:
    - common
    - db