---
- hosts: webservers
  user: vagrant
  sudo: yes
  gather_facts: no
  roles:
    - common
    - webservers
    - nginx

- hosts: dbservers
  user: vagrant
  sudo: yes
  gather_facts: no
  roles:
    - common
    - db