- name: install RVM
  shell: curl -L https://get.rvm.io | bash
  sudo: False

- name: source the rvm files
  shell: /bin/bash -c 'source /home/vagrant/.rvm/scripts/rvm'
  sudo: False

- name: install Ruby
  shell: /home/vagrant/.rvm/bin/rvm install --default $ruby creates=~/.rvm/rubies/$ruby
