#  Install Nginx
## ===============================================
   
- name: install nginx
  action: apt name=nginx

#- name: Generate the Nginx configuration file
#  copy: src=nginx.conf dest=/etc/nginx/nginx.conf