#  Install Nginx
## ===============================================
   
- name: install nginx
  action: apt name=nginx

- name: Generate the Nginx configuration file
  copy: src=app.conf dest=/etc/nginx/sites-available/app