---
# Install Postgresql latest version
#==============================================

- name: Install PostgreSQL dependencies
  action: apt pkg={{item}} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2

- name: Add postgres latest version ppa
  action: apt_repository repo=ppa:pitti/postgresql
   
- name: Update APT cache
  action: apt update_cache=yes
  
- name: Install db server packages
  action: apt pkg={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - postgresql-common

#- name: Add postgres user to admin group
#  action: user name=postgres groups=admin append=yes

- name: Start postgresql
  service: name=postgresql state=started 

- name: Create the postgresql deploy user 
  postgresql_user: name=deploy password=deploy login_host=127.0.0.1
  sudo: yes
  sudo_user: postgres
  
- name: Copy postgres hba config
  template: src=pg_hba.conf dest=/etc/postgresql/9.1/main/pg_hba.conf
  
- name: Copy postgres main config
  template: src=postgresql.conf dest=/etc/postgresql/9.1/main/postgresql.conf
  notify: Restart postgresql
