#  Install Ruby
## ===============================================
- name: Install dependencies
  apt: name=$item state=latest update_cache=yes
  with_items:
    - bison
    - openssl
    - libyaml-dev
    - autoconf
    - automake
    - libtool
    - pkg-config
    - libpq-dev
   
- name: Add Brightbox PPA
  action: apt_repository repo=ppa:brightbox/ruby-ng-experimental
              
- name: Install Ruby
  apt: name=$item state=latest update_cache=yes
  with_items:
    - ruby2.0
    - ruby2.0-dev
    - ruby2.0-doc
    
- name: Install some useful ruby gems
  action: gem name=$item state=present
  with_items:
    - bundler

#  Install Node.js for asset pipeline
## ===============================================

- name: add node repo
  apt_repository: repo=ppa:chris-lea/node.js

- name: update apt
  command: sudo apt-get update

- name: install node packages
  apt: name=nodejs state=latest update_cache=yes

