---
- name: nodejs dependencies
  apt: name=$item state=latest update_cache=yes
  with_items:
    - python-software-properties
    - python
    - g++
    - make

- name: add node repo
  apt_repository: repo=ppa:chris-lea/node.js

- name: update apt
  command: sudo apt-get update

- name: install node packages
  apt: name=nodejs state=latest update_cache=yes

- name: install nvm
  command: wget -qO- https://raw.github.com/creationix/nvm/master/install.sh | sh