- name: ensure apt cache is up to date
  action: apt update_cache=yes
  
- name: ensure packages are installed
  action: apt name={{item}}
  with_items:
      - postgresql
      - postgresql-contrib
      - postgresql-client
      - libpq-dev
      - python-psycopg2