---
- name: rmagick dependencies
  apt: name=$item state=latest update_cache=yes
  with_items:
    - imagemagick
    - libxml2-dev
    - libxslt1-dev
    - sqlite3
    - libsqlite3-dev
    - libmagickcore-dev 
    - libmagickwand-dev 
    - libmagick++-dev
