---
- hosts: vagrant
  user: vagrant

  vars:
    gem_path: ~/.rvm/gems/$ruby/bin
    ruby: ruby-head
    user: vagrant

  tasks:
    - name: update sudoers
      action: copy src=templates/sudoers dest=/etc/sudoers
      sudo: True

    - name: update apt
      action: command /usr/bin/apt-get update
      sudo: True

    - name: update cache 
      apt: update_cache=yes
      sudo: True

    - name: install essential packages
      apt: pkg=$item state=installed
      sudo: True
      with_items:
        - build-essential
        - curl
        - git
        - python-dev
        - python-setuptools
        - python-software-properties

    - include: tasks/rvm.yml
    
    - name: install bundler
      gem: name=bundler state=latest
      
    # Install postgres
    - include: tasks/postgres.yml
    
    # Install Redis
    - include: tasks/redis.yml
