---
- hosts: vagrant
  user: vagrant
  gather_facts: no

  vars:
    gem: /home/vagrant/.rvm/rubies/ruby-head/bin/gem
    ruby: ruby-head

  tasks:
    # Basic server config and setup
    - include: tasks/configure.yml
    
    # Install components
    - include: tasks/rvm.yml
    - include: tasks/postgres.yml
    # We need a JS runtime for the asset pipeline
    - include: tasks/node.yml
    - include: tasks/nginx.yml
    
  handlers:
    - name: restart postgresql
      action: service name=postgresql state=restarted
      sudo: True
        
- hosts: vagrant
  sudo: True
  user: vagrant
  sudo_user: postgres

  tasks:
    - name: create a vagrant database user
      action: postgresql_user user=vagrant password=password role_attr_flags=CREATEDB 
