---
- name: update apt
  action: command /usr/bin/apt-get update
  sudo: true

- name: update cache 
  apt: update_cache=yes
  sudo: true

# Install anything essential that you need here
- name: install essential packages
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
    - build-essential
    - curl
    - git
    - emacs
    - python-dev
    - sqlite3
    - python-setuptools
    - python-software-properties
    - libsqlite3-dev
    - make
    - g++